efundi/PDF-Marker

src/app/modules/application/layout/header/header.component.html, src/app/modules/application/layout/header/header.component.ts, src/app/modules/pdf-marker/components/home/home.component.html
Move button to top left, to avoid scrolling the button in view
=> NAM-288 Move menu collapse button to top left

src/app/modules/application/shared/shared.module.ts, src/app/modules/pdf-marker/components/assignment-marking-page/assignment-marking-page.component.html, src/app/modules/pdf-marker/components/assignment-marking-page/assignment-marking-page.component.ts, src/app/modules/pdf-marker/components/assignment-marking/assignment-marking-session.service.ts, src/app/modules/pdf-marker/components/icons/icons.component.html, src/app/modules/pdf-marker/components/icons/icons.component.scss, src/app/modules/pdf-marker/components/icons/icons.component.ts, src/app/modules/pdf-marker/components/mark-type-icon/mark-type-icon.component.ts
=> NAM-289 Zooming

package-lock.json, package.json, server.ts, src/app/modules/application/core/services/electron.service.ts, src/app/modules/application/shared/components/marking-highlight-modal/marking-highlight-modal.component.html, src/app/modules/application/shared/components/marking-highlight-modal/marking-highlight-modal.component.scss, src/app/modules/application/shared/components/marking-highlight-modal/marking-highlight-modal.component.spec.ts, src/app/modules/application/shared/components/marking-highlight-modal/marking-highlight-modal.component.ts, src/app/modules/application/shared/info-objects/highlighter-color.ts, src/app/modules/application/shared/info-objects/mark.info.ts, src/app/modules/application/shared/shared.module.ts, src/app/modules/pdf-marker/components/assignment-marking-page/assignment-marking-page.component.html, src/app/modules/pdf-marker/components/assignment-marking-page/assignment-marking-page.component.scss, src/app/modules/pdf-marker/components/assignment-marking-page/assignment-marking-page.component.ts, src/app/modules/pdf-marker/components/assignment-marking/assignment-marking-session.service.ts, src/app/modules/pdf-marker/components/icons/icons.component.html, src/app/modules/pdf-marker/components/icons/icons.component.scss, src/app/modules/pdf-marker/components/icons/icons.component.ts, src/app/modules/pdf-marker/components/mark-type-highlight/mark-type-highlight.component.html, src/app/modules/pdf-marker/components/mark-type-highlight/mark-type-highlight.component.scss, src/app/modules/pdf-marker/components/mark-type-highlight/mark-type-highlight.component.spec.ts, src/app/modules/pdf-marker/components/mark-type-highlight/mark-type-highlight.component.ts, src/app/modules/pdf-marker/components/mark-type-icon/mark-type-icon.component.html, src/app/modules/pdf-marker/components/mark-type-icon/mark-type-icon.component.scss, src/app/modules/pdf-marker/components/mark-type-icon/mark-type-icon.component.ts, src/app/modules/pdf-marker/info-objects/icon-type.enum.ts, src/app/modules/pdf-marker/pdf-marker.module.ts, src/styles.scss
- Fix native annotations (some parameters was not set)
- Upgrade annotation library
- Highlighter tool
- All editor context menus are now dark grey
=> NAM-292 Highlighting

src/app/modules/pdf-marker/components/mark-type-highlight/mark-type-highlight.component.html, src/app/modules/pdf-marker/components/mark-type-highlight/mark-type-highlight.component.scss
- Show small comment icon on highlight if the highlight has a section label
=> NAM-292 Show comment icon on highlight

package-lock.json, package.json, src-express/rest/assignment.ts, src-express/rest/import.ts, src-express/rest/settings.ts, src-express/rest/working-folder.ts, src-express/utils.ts, src/app/modules/application/core/services/sakai.service.ts, src/app/modules/application/shared/components/file-explorer/file-explorer.component.ts, src/app/modules/application/shared/services/assignment.service.ts, src/app/modules/pdf-marker/components/assignment-overview/assignment-overview.component.ts, src/app/modules/pdf-marker/components/assignment-workspace-manage-modal/assignment-workspace-manage-modal.component.ts, src/app/modules/pdf-marker/components/assignment-workspace-overview/assignment-workspace-overview.component.ts, src/app/modules/pdf-marker/components/create-assignment/create-assignment.component.ts, src/app/modules/pdf-marker/components/import/import.component.ts, src/app/modules/pdf-marker/components/working-folder/working-folder.component.ts, src/app/modules/pdf-marker/services/pdfm-utils.service.spec.ts, src/app/modules/pdf-marker/services/pdfm-utils.service.ts
- Fix creating multiple assignments on linux
- Improve error handling when trying to move a workspace
- Remove code where the front-end tries to access the filesystem 
- Minor code style cleanup
- Remove more instances where `locutus` library and use NodeJS native utils
=> NAM-269 Fix Workspace Move Error

main.ts, package.json, preload.ts, src-electron/constants.ts, src-electron/ipc/assignment.handler.ts, src-electron/ipc/workspace.handler.ts, src-electron/pdf/marking-annotations.ts, src/app/components/assignment-marking-page/assignment-marking-page.component.ts, src/app/components/assignment-marking/assignment-marking.component.html, src/app/components/assignment-marking/assignment-marking.component.ts, src/app/components/assignment-overview/assignment-overview.component.html, src/app/components/assignment-workspace-overview/assignment-workspace-overview.component.ts, src/app/components/create-assignment/create-assignment.component.ts, src/app/components/icons/icons.component.html, src/app/components/icons/icons.component.scss, src/app/components/rubric/rubric.component.ts, src/app/components/side-navigation/side-navigation.component.ts, src/app/components/working-folder/working-folder.component.ts, src/app/services/app.service.ts, src/app/services/assignment.service.ts, src/shared/info-objects/mark.info.ts, src/shared/info-objects/submission.info.ts, src/shared/ipc/assignment.ipc-service.ts
- Migrate `.marks.json` schema
- Rotate PDF on screen
- Export rotated PDF
=> NAM-290 WIP rotate

src-electron/constants.ts, src-electron/ipc/assignment.handler.ts, src-electron/pdf/marking-annotations.ts, src/app/components/assignment-list/assignment-list.component.ts, src/app/components/assignment-marking/assignment-marking.component.html, src/app/components/assignment-marking/assignment-marking.component.ts, src/app/components/assignment-overview/assignment-overview.component.html, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/components/assignment-workspace-manage-modal/assignment-workspace-manage-modal.component.html, src/app/components/assignment-workspace-manage-modal/assignment-workspace-manage-modal.component.ts
- Fix date modified date format was wrong
- opening an submission from the default workspace didnt open the tree
- better error messages when failling to save marks
- Rubrics didnt work
- Update UI so that the user doesn't attempt to rename the Default Workspace
=> NAM-290 Fixes

package.json, src-electron/ipc/workspace.handler.ts, src/app/components/assignment-workspace-manage-modal/assignment-workspace-manage-modal.component.ts, src/app/components/create-assignment/create-assignment.component.ts, src/app/components/import/import.component.ts, src/app/components/working-folder/working-folder.component.html, src/app/components/working-folder/working-folder.component.ts
- Show default workspace in places where required
- Add Default workspace to list of available workspaces from backend
=> NAM-265 Fixes for default workspace

main.ts, preload.ts, src-electron/ipc/assignment.handler.ts, src-electron/ipc/rubric.handler.ts, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/components/file-explorer-modal/file-explorer-modal.component.html, src/app/components/import/import.component.ts, src/app/components/rubric-import/rubric-import.component.ts, src/app/components/rubric-view-modal/rubric-view-modal.component.html, src/app/components/rubric-view-modal/rubric-view-modal.component.scss, src/app/components/rubric-view-modal/rubric-view-modal.component.ts, src/app/components/rubric/rubric.component.html, src/app/components/rubric/rubric.component.scss, src/app/services/assignment.service.ts, src/shared/ipc/assignment.ipc-service.ts
- Fix rubric template prompt never stops the busy indicator
- Fix change rubric doesn't save
- Layout fixes for rubric modal
=> NAM-297 Fixes

package.json, src/app/components/assignment-overview/assignment-overview.component.html, src/app/components/assignment-overview/assignment-overview.component.scss, src/app/components/assignment-overview/assignment-overview.component.ts
- Fix sorting getting stuck
- Fix sorting on name, not surname + name
- Fix padding on date modified column
- Fix alignment of status column
=> NAM-287 Fixes for assignment overview

src-electron/ipc/assignment.handler.ts, src-electron/utils.ts, src/app/app.module.ts, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/components/home/home.component.ts, src/app/components/rubric-import/rubric-import.component.ts, src/app/components/rubric-view-modal/rubric-view-modal.component.ts, src/app/services/app.service.ts, src/app/services/assignment.service.ts
- Fix changing rubrics didnt update screen
- Fix grades.csv file corrupted during zip import
- Fix importing same generic zip on windows didn't work as expected
=> NAM-297 Bug fixes

angular.json, src/styles.scss
Remove prebuilt indigo theme, instead build custom theme using grey pallete as default
=> NAM-297 Styling

main.ts, preload.ts, src-electron/ipc/import.handler.ts, src/app/components/import/import.component.html, src/app/components/import/import.component.ts, src/app/services/import.service.ts, src/shared/ipc/import.ipc-service.ts
- Improve validation of zip file
- Refactor zip validation IPC service to validate based on expected file type
- Use proper form apis for subscribing to form changes and altering validations
=> NAM-316 Improve validation

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/markers-manage/markers-manage.component.html, src/app/components/markers-manage/markers-manage.component.spec.ts, src/app/components/markers-manage/markers-manage.component.ts, src/app/components/menu/menu.component.ts, src/app/utils/routes.enum.ts, src/shared/info-objects/setting.info.ts
- Added new menu item for Markers
- Added placeholder page for Markers screen
=> NAM-314 Added new menu item for markers

src-electron/ipc/assignment.handler.ts, src/app/components/create-assignment/create-assignment.component.ts
- Remove validation on electron code - front-end handles it
- Improve UI error handling
=> NAM-317 Fix validation

main.ts, preload.ts, src-electron/ipc/assignment.handler.ts, src-electron/ipc/import.handler.ts, src-electron/migration/assignment.migration.ts, src/app/app.module.ts, src/app/components/assignment-list/assignment-list.component.ts, src/app/components/assignment-marking/assignment-marking-toolbar/assignment-marking-toolbar.component.html, src/app/components/assignment-marking/assignment-marking-toolbar/assignment-marking-toolbar.component.scss, src/app/components/assignment-marking/assignment-marking-toolbar/assignment-marking-toolbar.component.ts, src/app/components/assignment-marking/assignment-marking.component.html, src/app/components/assignment-marking/assignment-marking.component.ts, src/app/components/assignment-marking/preview-marks/preview-marks.component.html, src/app/components/assignment-marking/preview-marks/preview-marks.component.scss, src/app/components/assignment-marking/preview-marks/preview-marks.component.spec.ts, src/app/components/assignment-marking/preview-marks/preview-marks.component.ts, src/app/components/assignment-overview/assignment-overview.component.html, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/components/submission-navigator/submission-navigator.component.ts, src/app/components/yes-and-no-confirmation-dialog/yes-and-no-confirmation-dialog.component.html, src/app/services/assignment.service.ts, src/shared/info-objects/assignment-settings.info.ts, src/shared/ipc/assignment.ipc-service.ts
- Ability to mark as a "marker"
- Export as marker
- Cleanup unused code
- Restore previously delete "finalizeAssignment" and rename to "previewMarks"
=> NAM-330 Marker export

main.ts, package-lock.json, package.json, preload.ts, src-electron/ipc/assignment.handler.ts, src-electron/ipc/import.handler.ts, src/app/app.module.ts, src/app/components/assignment-overview/assignment-overview.component.html, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/components/assignment-overview/import-marker-modal/import-marker-modal.component.html, src/app/components/assignment-overview/import-marker-modal/import-marker-modal.component.scss, src/app/components/assignment-overview/import-marker-modal/import-marker-modal.component.spec.ts, src/app/components/assignment-overview/import-marker-modal/import-marker-modal.component.ts, src/app/services/import.service.ts, src/shared/info-objects/lecture-import.info.ts, src/shared/ipc/import.ipc-service.ts
- Work in progress lecture import
- Fix `glob` dependency issue
=> NAM-332 WIP lecture import

src-electron/ipc/application.handler.ts, src-electron/ipc/assignment.handler.ts, src/app/components/assignment-marking/assignment-marking.component.ts, src/app/components/assignment-overview/assignment-overview.component.html, src/app/utils/utils.ts, src/shared/info-objects/assignment-settings.info.ts
- Implement Not Marked stated for Finalized and Exported for review submissions with no marks
- Fix NodeJS Deprecation warnings
=> NAM-330 Not Marked state

main.ts, preload.ts, src-electron/ipc/assignment.handler.ts, src/app/components/assignment-overview/allocate-markers-modal/allocate-markers-modal.component.ts, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/services/assignment.service.ts, src/shared/info-objects/export-assignments-request.ts, src/shared/ipc/assignment.ipc-service.ts
- Minor code cleanup
- Reuse exportAssignment electron handler
- Add validation to export path
=> Refactoring

src-electron/ipc/import.handler.ts, src-electron/ipc/workspace.handler.ts, src/app/components/assignment-workspace-manage-modal/assignment-workspace-manage-modal.component.html, src/app/components/assignment-workspace-manage-modal/assignment-workspace-manage-modal.component.ts, src/app/components/assignment-workspace-overview/assignment-workspace-overview.component.html, src/app/components/assignment-workspace-overview/assignment-workspace-overview.component.ts, src/app/components/working-folder/working-folder.component.ts
- Fix renaming workspaces
- Fix duplicate import on windows overlaying existing assignment
=> NAM-325 Workspace and import fixes

src-electron/ipc/assignment.handler.ts, src-electron/worker-pool.ts, src-electron/zip.ts, src/app/components/assignment-overview/assignment-overview.component.ts, src/app/utils/utils.ts
- Fix export not including files that start with a dot e.g. `.settings.json`
- Fix finalize should not be available while submissions are being moderated
- Fix submission state should not change when moderated submissions are being edited
=> NAM-334 Fixes

src-electron/ipc/assignment.handler.ts, src-electron/ipc/rubric.handler.ts, src/app/components/assignment-overview/assignment-overview.component.html, src/app/components/assignment-overview/assignment-overview.component.scss
- Keep no submission state on finalize
- Fix windows file paths when using `glob`
- Show grey text for submissions with no files
=> NAM-339 No submission fixes

src-electron/ipc/assignment.handler.ts
Update allocation to owner when editing a "not marked" submission
=> NAM-356 Update allocation

src-electron/constants.ts, src-electron/ipc/assignment.handler.ts, src-electron/ipc/convert.handler.ts, src-electron/ipc/import.handler.ts, src-electron/utils.ts, src-electron/worker-pool.ts, src/app/components/create-assignment/create-assignment.component.html, src/app/components/create-assignment/create-assignment.component.scss, src/app/components/import/import.component.html, src/app/components/import/import.component.scss, src/app/components/import/import.component.ts, src/app/components/rubric-import/rubric-import.component.html, src/app/components/rubric-import/rubric-import.component.scss, src/app/services/import.service.ts, src/app/services/ipc.utils.ts
- Surface errors when finalize fails
- Improve error handling when file conversions fail
- other small fixes...
=> NAM-354 File conversion

src-electron/ipc/convert.handler.ts, src/app/components/create-assignment/create-assignment.component.html, src/app/components/create-assignment/create-assignment.component.ts
- Update message when libre office version could not be determined
- Fix incorrect path used to redirect to when editing an existing manual assignment
- Fix checking for unsaved changes on manual assignment manage screen
=> NAM-354 Minor fixes

src-electron/ipc/assignment.handler.ts, src/app/components/submission-navigator/submission-navigator.component.ts
- Update submission state when rubric is changed
- Fix build error
=> NAM-358 Update submission state

build/installer.nsh, package.json
Link to Libre Installer updated to 7.5.4
=> Updated the LibreOffice download link to version 7.5.4

src-electron/constants.ts, src-electron/ipc/assignment.handler.ts, src-electron/ipc/import.handler.ts
- Fix importing markers file
- Fix finalize containing `.backup` directory
- Fix group assignment csv format
=> NAM-367 Group assignment import

docs/debugging.md, main.ts, preload.ts, src-electron/ipc/config.handler.ts, src-electron/ipc/import.handler.ts, src/app/components/markers-manage/markers-manage.component.ts, src/app/components/submission-navigator/submission-navigator.component.ts, src/app/services/settings.service.ts, src/app/utils/logging.ts
- Fix group import
- Ability to set debug log level
=> NAM-367 Group import fix
